1) create a list, accept 5 numbers , store them in the list and finally convert that list to numpy array.

In [ ]:
import numpy as np

ls=[]
for i in range(5):
    num=int(input("Enter the number : "))
    ls.append(num)
arr=np.array(ls)
print(arr)

Enter the number : 5
Enter the number : 9
Enter the number : 7
Enter the number : 1
Enter the number : 3
[5 9 7 1 3]


2) create numpy array of 5 numbers and print their sum

In [ ]:
import numpy as np

arr=np.array([5,4,3,9,8])
print("Given array is : ",arr)
print("Sum of elements of array:",sum(arr))
print("Sum of elements of array: ",np.sum(arr,axis=0))

sum=0
for i in range(arr.__len__()):
    sum+=arr[i]
print("Sum of elements of array: (Using loop): ",sum)

Given array is :  [5 4 3 9 8]
Sum of elements of array: 29
Sum of elements of array:  29
Sum of elements of array: (Using loop):  29


3) create numpy double dimension array of 3*3 to store your initial and display them in a tabular form.

In [ ]:
import numpy as np

arr = np.array([['M','D','K'],['M','A','H'],['E','S','H']])

for i in range (arr.__len__()):
    for j in range (arr[i].__len__()):
        print(arr[i][j],end="\t")
    print("\n")

#or
print("*******")

for i in arr:
    for j in i:
      print(j,end="\t")
    print("\n")

M	D	K	

M	A	H	

E	S	H	

*******
M	D	K	

M	A	H	

E	S	H	



4) create one-d numpy array of 12 elements , accept 12 numbers and display them. Now convert this one-d array into (4*3) two-d array and display it in a tabular form.

In [ ]:
import numpy as np

ls=[]
for i in range (12):
  num=int(input(f"Enter number {i+1} : "))
  ls.append(num)
ar = np.array(ls)
print(ar)
ar.shape=(4,3)
print("*********")
for i in ar:
  for j in i:
    print(j,end="\t")
  print("\n")

Enter number 1 : 8
Enter number 2 : 12
Enter number 3 : 3
Enter number 4 : 4
Enter number 5 : 6
Enter number 6 : 10
Enter number 7 : 11
Enter number 8 : 9
Enter number 9 : 7
Enter number 10 : 2
Enter number 11 : 13
Enter number 12 : 1
[ 8 12  3  4  6 10 11  9  7  2 13  1]
*********
8	12	3	

4	6	10	

11	9	7	

2	13	1	



5) create two double dimension array and arrange (stack) them using "axis=0" "axis=1" and  "axis=2".

In [ ]:
import numpy as np

arr1=np.array([[1,2,4],[3,5,8]])
arr2=np.array([[11,14,13],[9,7,1]])

arr3=np.stack((arr1,arr2),axis=0)
print(arr3)
print("*************")
arr3=np.stack((arr1,arr2),axis=1)
print(arr3)
print("*************")
arr3=np.stack((arr1,arr2),axis=2)
print(arr3)

[[[ 1  2  4]
  [ 3  5  8]]

 [[11 14 13]
  [ 9  7  1]]]
*************
[[[ 1  2  4]
  [11 14 13]]

 [[ 3  5  8]
  [ 9  7  1]]]
*************
[[[ 1 11]
  [ 2 14]
  [ 4 13]]

 [[ 3  9]
  [ 5  7]
  [ 8  1]]]


6) create two one-d arrays and then find out:

   a) common elements of both the array
    
  b) unique elements of first array
      
  c) unique elements of second array

In [ ]:
import numpy as np

arr1=np.array([1,2,8,6,4,6,3,4,8])
arr2=np.array([3,5,4,7,8,6,1])
a=np.intersect1d(arr1,arr2)
print(a)
print("***************")
a=np.setdiff1d(arr1,arr2)
print(a)
print("***************")
a=np.setdiff1d(arr2,arr1)
print(a)

[1 3 4 6 8]
***************
[2]
***************
[5 7]


7) accept no.of rows and no. of cols from the user , create two-d array accordingly. Now calculate the sum as per "axis=0" and "axis=1"

In [ ]:
rowno=int(input("Enter number of rows : "))
colno=int(input("Enter number of columns : "))
ls=[]
print(f"Enter {rowno*colno} numbers : ")
for i in range(rowno*colno):
    num=int(input())
    ls.append(num)
arr=np.array(ls).reshape(rowno,colno)
print(arr)
print("**************")
sum=np.sum(arr,axis=0)
print("Sum as per axis=0")
print(sum)
print("**************")
sum=np.sum(arr,axis=1)
print("Sum as per axis=1")
print(sum)

Enter number of rows : 2
Enter number of columns : 2
Enter 4 numbers : 
6
3
2
7
[[6 3]
 [2 7]]
**************
Sum as per axis=0
[ 8 10]
**************
Sum as per axis=1
[9 9]



8) declare two 2d arrays and calculate the sum as per "axis=0" "axis=1" and "axis=2"

In [ ]:
import numpy as np

arr1=np.array([[1,2,4],[3,5,8]])
arr2=np.array([[11,14,13],[9,7,1]])

arr3=np.sum((arr1,arr2),axis=0)
print(arr3)
print("*************")
arr3=np.sum((arr1,arr2),axis=1)
print(arr3)
print("*************")
arr3=np.sum((arr1,arr2),axis=2)
print(arr3)

[[12 16 17]
 [12 12  9]]
*************
[[ 4  7 12]
 [20 21 14]]
*************
[[ 7 16]
 [38 17]]


9) create two-d array ,display it. Now accept a number from user and perform all arithmetic operations on each and every element of the array using that number.

In [ ]:
import numpy as np

np.random.seed(5)
arr=np.random.randint(1,50,9).reshape(3,3)
print(arr)
num=int(input("Enter the number to perform maths operation = "))
print("Add operation")
print(arr.__add__(num))
print("Subtract operation")
print(arr.__sub__(num))
print("Multiply operation")
print(arr.__mul__(num))
print("Division operation")
print(arr.__truediv__(num))

[[36 15 48]
 [39 17 10]
 [ 9 37 40]]
Enter the number to perform maths operation = 5
Add operation
[[41 20 53]
 [44 22 15]
 [14 42 45]]
Subtract operation
[[31 10 43]
 [34 12  5]
 [ 4 32 35]]
Multiply operation
[[180  75 240]
 [195  85  50]
 [ 45 185 200]]
Division operation
[[7.2 3.  9.6]
 [7.8 3.4 2. ]
 [1.8 7.4 8. ]]


10) Accept start, end and how many numbers to be generated and then using "linspace" create numpy array.

In [1]:
import numpy as np
start=int(input("Enter the start point="))
end=int(input("Enter the end point="))
sep=int(input("Enter how many numbers to be generated="))

arr=np.linspace(start,end,sep)
print(arr)

Enter the start point=5
Enter the end point=15
Enter how many numbers to be generated=5
[ 5.   7.5 10.  12.5 15. ]


11) create one-d array of 8 numbers and then using "slicing" concept,

a) print numbers from 1 to 4

b) print all the numbers from 3rd position

c) print last 3 numbers

In [5]:
arr=[10,20,30,40,50,60,70,80]

print("Numbers from 1 to 4")
print(arr[1:5])

print("all numbers from 3rd position")
print(arr[3:])

print("last 3 numbers")
print(arr[-3:])

Numbers from 1 to 4
[20, 30, 40, 50]
all numbers from 3rd position
[40, 50, 60, 70, 80]
last 3 numbers
[60, 70, 80]



12) create 2 d array (4*3) with following values:

[[10,20,30,40],[50,60,70,80],[90,100,110,120]]

now using array slicing concept display following values
* a) display   50  60  70  80
* b) display 100 and 110
* c) display 30 70 and 110
* d) display 50  60  90 and 100

In [13]:
import numpy as np
arr=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])

print("Answer of (a)")
print(arr[1,:3])

print("Answer of (b)")
print(arr[2,1:3])

print("Answer of (c)")
print(arr[1:,:2])

Answer of (a)
[50 60 70]
Answer of (b)
[100 110]
Answer of (c)
[[ 50  60]
 [ 90 100]]
